name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.4.0'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn install
      # check code
      - name: Install EditorConfig Checker
        run: |
          curl -LO https://github.com/editorconfig-checker/editorconfig-checker/releases/latest/download/ec-linux-amd64.tar.gz
          tar -xvzf ec-linux-amd64.tar.gz
          sudo mv bin/ec-linux-amd64 /usr/local/bin/ec

      - name: Check .editorconfig rules
        run: ec check

      - name: Apply formatting tools
        run: |
          prettier --write "**/*.{js,jsx,ts,tsx,json,css,scss,html,md}"
          find . -name "*.java" | xargs java -jar google-java-format.jar --replace
